from playwright.sync_api import sync_playwright

login = "williamb"
senha = "william2012"

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://si3.ufc.br/")
    page.fill("input[name='user.login']", login)
    page.wait_for_timeout(750)
    page.fill("input[name='user.senha']", senha)
    page.wait_for_timeout(750)
    page.click("input[name='entrar']")
    page.wait_for_timeout(750)
    page.click("a[id='btnNaoResponderContinuar']")
    page.wait_for_timeout(750)
    page.click("input[id='btnSimLembrarQuestionario']")
    page.wait_for_timeout(750)
    page.click("input[type='submit']")
    page.wait_for_timeout(750)
    page.click("a[href='/sigaa/verPortalDiscente.do']")
    page.wait_for_timeout(750)
    page.click("tbody tr td:first-child")
    page.wait_for_timeout(750)
    page.click("tbody tr:nth-last-child(3)")
    page.wait_for_timeout(750)
    page.click("div[id='cmSubMenuID9'] tr:nth-child(2) td:nth-child(2)")
    page.wait_for_timeout(750)
    page.click("select[id='form:selectUnidade']")
    page.wait_for_timeout(750)
    page.select_option("select[id='form:selectUnidade']", value='959')
    page.wait_for_timeout(750)
    page.click("select[id='form:selectCurso']")
    page.wait_for_timeout(750)
    page.select_option("select[id='form:selectCurso']", value='657484')
    page.wait_for_timeout(2000)
    page.click("input[id='form:buttonBuscar']")
    page.wait_for_timeout(10000)
    inner = page.inner_html("table[id='lista-turmas']")
    print(inner)
    browser.close()
